import os
import io
import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image as RLImage, Table, TableStyle

def generate_pdf_report(image_bytes, prediction_data):
    """
    Generates a PDF report containing the original image and the prediction results.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    elements = []
    styles = getSampleStyleSheet()

    # Custom Styles
    title_style = styles['Heading1']
    title_style.alignment = 1 # Center
    
    subtitle_style = styles['Heading2']
    
    normal_style = styles['Normal']
    normal_style.fontSize = 11

    # Title
    elements.append(Paragraph("Diabetic Retinopathy Assessment Report", title_style))
    elements.append(Spacer(1, 10))
    elements.append(Paragraph(f"Date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", normal_style))
    elements.append(Spacer(1, 20))

    # Try to load and add the image
    try:
        # Save bytes to a temporary file locally so reportlab can read it
        img_temp_path = "temp_report_img.jpg"
        with open(img_temp_path, "wb") as f:
            f.write(image_bytes)
        
        img = RLImage(img_temp_path, width=200, height=200)
        elements.append(img)
        elements.append(Spacer(1, 20))
    except Exception as e:
        elements.append(Paragraph("*Unable to render original image.*", normal_style))
        elements.append(Spacer(1, 20))

    # Prediction Data
    elements.append(Paragraph("Assessment Results", subtitle_style))
    elements.append(Spacer(1, 10))

    pred_class = prediction_data['class_id']
    pred_label = prediction_data['label']
    confidence = f"{prediction_data['confidence']}%"
    desc = prediction_data['description']

    data = [
        ['Predicted Class:', str(pred_class)],
        ['Severity Label:', pred_label],
        ['Confidence Score:', confidence]
    ]

    t = Table(data, colWidths=[120, 300])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.whitesmoke),
        ('TEXTCOLOR', (0,0), (-1,-1), colors.black),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('FONTNAME', (0,0), (-1,-1), 'Helvetica'),
        ('FONTSIZE', (0,0), (-1,-1), 12),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ('GRID', (0,0), (-1,-1), 0.5, colors.grey)
    ]))
    elements.append(t)
    elements.append(Spacer(1, 20))

    # Medical Note
    elements.append(Paragraph("Medical Note & Recommendation:", subtitle_style))
    elements.append(Spacer(1, 10))
    elements.append(Paragraph(desc, normal_style))
    elements.append(Spacer(1, 30))

    # Disclaimer
    disclaimer = ("DISCLAIMER: This report is generated by an Artificial Intelligence (Hybrid Quantum-Classical) "
                  "system intended for research purposes. It must not be used as a substitute for professional "
                  "medical advice, diagnosis, or treatment. Always seek the advice of an ophthalmologist or "
                  "other qualified healthcare provider with any questions you may have regarding a medical condition.")
    
    disclaimer_style = ParagraphStyle('Disclaimer', parent=styles['Normal'], textColor=colors.red, fontSize=9)
    elements.append(Paragraph(disclaimer, disclaimer_style))

    # Build PDF
    doc.build(elements)
    
    # Cleanup temp image
    if os.path.exists("temp_report_img.jpg"):
        os.remove("temp_report_img.jpg")
        
    buffer.seek(0)
    return buffer.getvalue()
